class CONFIG:
    WSL = False
    LOCAL = True
    TRAIN = True

    RANDOM_STATE = 42

    DATE_COL = "date_id"
    DROP_COL = [
        "US_Stock_GOLD_adj_open",
        "US_Stock_GOLD_adj_high",
        "US_Stock_GOLD_adj_low",
        "US_Stock_GOLD_adj_close",
        "US_Stock_GOLD_adj_volume",
        "US_Stock_X_adj_open",
        "US_Stock_X_adj_high",
        "US_Stock_X_adj_low",
        "US_Stock_X_adj_close",
        "US_Stock_X_adj_volume",
    ]
    NUM_TARGET_COLUMNS = 424

    if LOCAL:
        TRAIN_X_PATH = "data/train.csv"
        TRAIN_Y_PATH = "data/train_labels.csv"
        TEST_PATH = "data/test.csv"
        TARGET_PAIRS_PATH = "data/target_pairs.csv"
    else:
        BASE_PATH = "/kaggle/input/mitsui-commodity-prediction-challenge"
        TRAIN_X_PATH = f"{BASE_PATH}/train.csv"
        TRAIN_Y_PATH = f"{BASE_PATH}/train_labels.csv"
        TEST_PATH = f"{BASE_PATH}/test.csv"
        TARGET_PAIRS_PATH = f"{BASE_PATH}/target_pairs.csv"
        MODEL_PATH = "/kaggle/input/mitsui-nn/pytorch/test/1/sample.pth"

    if WSL:
        mount = "/mnt/c/Users/Admin/Desktop/Personal-Projects/Kaggle/MITSUI&CO. Commodity Prediction Challenge/"
        TRAIN_X_PATH = f"{mount}{TRAIN_X_PATH}"
        TRAIN_Y_PATH = f"{mount}{TRAIN_Y_PATH}"
        TEST_PATH = f"{mount}{TEST_PATH}"

    N_FOLDS = 5
    MAX_TRAIN_DATE = 1870  # 1826

    # fmt: off
    ASSETS = {
        "LME": ["AH", "CA", "PB", "ZS"],
        "JPX": [
            "Gold_Mini_Futures",
            "Gold_Rolling-Spot_Futures",
            "Gold_Standard_Futures",
            "Platinum_Mini_Futures",
            "Platinum_Standard_Futures",
            "RSS3_Rubber_Futures"
        ],
        "US_STOCK": [
            "ACWI", "AEM", "AG", "AGG", "ALB", "AMP", "BCS", "BKR", "BND", "BNDX", "BP",
            "BSV", "CAT", "CCJ", "CLF", "COP", "CVE", "CVX", "DE", "DVN", "EEM", "EFA",
            "EMB", "ENB", "EOG", "EWJ", "EWT", "EWY", "EWZ", "FCX", "FNV", "FXI", "GDX",
            "GDXJ", "GLD", "GOLD", "HAL", "HES", "HL", "IAU", "IEF", "IEMG", "IGSB", "JNK",
            "KGC", "KMI", "LQD", "LYB", "MBB", "MPC", "MS", "NEM", "NUE", "NUGT", "OIH",
            "OKE", "OXY", "PAAS", "RIO", "RSP", "RY", "SCCO", "SHEL", "SHY", "SLB", "SLV",
            "SPIB", "SPTL", "SPYV", "STLD", "TD", "TECK", "TIP", "TRGP", "URA", "VALE",
            "VCIT", "VCSH", "VEA", "VGIT", "VGK", "VGLT", "VGSH", "VT", "VTV", "VWO",
            "VXUS", "VYM", "WMB", "WPM", "X", "XLB", "XLE", "XOM", "YINN"
        ],
        "FX": [
            "AUDJPY", "AUDUSD", "CADJPY", "CHFJPY", "EURAUD", "EURGBP", "EURJPY",
            "EURUSD", "GBPAUD", "GBPJPY", "GBPUSD", "NZDJPY", "NZDUSD", "USDCHF",
            "USDJPY", "ZARJPY", "ZARUSD", "NOKUSD", "NOKEUR", "CADUSD", "AUDNZD",
            "EURCHF", "EURCAD", "AUDCAD", "GBPCHF", "EURNZD", "AUDCHF", "GBPNZD",
            "GBPCAD", "CADCHF", "NZDCAD", "NZDCHF", "ZAREUR", "NOKGBP", "NOKCHF",
            "ZARCHF", "NOKJPY", "ZARGBP"
        ],
    }

    PAIRS = [('LME_CA_Close', 'US_Stock_HAL_adj_close'),
        ('FX_ZARJPY', 'JPX_Gold_Standard_Futures_Close'),
        ('US_Stock_DVN_adj_close', 'LME_PB_Close'),
        ('FX_EURNZD', 'LME_PB_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_VGIT_adj_close'),
        ('FX_AUDCHF', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_URA_adj_close'),
        ('LME_ZS_Close', 'US_Stock_VYM_adj_close'),
        ('US_Stock_VYM_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_ZS_Close', 'US_Stock_EFA_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_AUDUSD'),
        ('US_Stock_CAT_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_PB_Close', 'US_Stock_WMB_adj_close'),
        ('LME_PB_Close', 'LME_CA_Close'),
        ('US_Stock_ENB_adj_close', 'LME_PB_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_CADCHF'),
        ('US_Stock_MPC_adj_close', 'LME_CA_Close'),
        ('LME_ZS_Close', 'JPX_Platinum_Standard_Futures_Close'),
        ('US_Stock_VGK_adj_close', 'LME_CA_Close'),
        ('FX_ZARUSD', 'LME_AH_Close'),
        ('LME_AH_Close', 'US_Stock_VEA_adj_close'),
        ('FX_EURAUD', 'LME_PB_Close'),
        ('LME_ZS_Close', 'US_Stock_VGIT_adj_close'),
        ('LME_CA_Close', 'FX_GBPJPY'),
        ('US_Stock_SPYV_adj_close', 'LME_AH_Close'),
        ('LME_CA_Close', 'US_Stock_LYB_adj_close'),
        ('FX_NZDUSD', 'LME_ZS_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_KMI_adj_close'),
        ('LME_AH_Close', 'US_Stock_TD_adj_close'),
        ('LME_AH_Close', 'US_Stock_SCCO_adj_close'),
        ('US_Stock_GLD_adj_close', 'LME_PB_Close'),
        ('US_Stock_RSP_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_TD_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_KMI_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_AMP_adj_close'),
        ('LME_CA_Close', 'US_Stock_VYM_adj_close'),
        ('FX_NOKJPY', 'LME_ZS_Close'),
        ('LME_CA_Close', 'FX_NZDJPY'),
        ('LME_AH_Close', 'FX_NOKEUR'),
        ('LME_PB_Close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_PB_Close', 'US_Stock_VALE_adj_close'),
        ('LME_AH_Close', 'FX_AUDCHF'),
        ('LME_AH_Close', 'LME_PB_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_XOM_adj_close'),
        ('FX_ZARCHF', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_ZARJPY', 'LME_PB_Close'),
        ('FX_EURCAD', 'LME_ZS_Close'),
        ('LME_CA_Close', 'US_Stock_HES_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_XOM_adj_close'),
        ('LME_AH_Close', 'US_Stock_XLE_adj_close'),
        ('LME_ZS_Close', 'US_Stock_IEMG_adj_close'),
        ('FX_ZARCHF', 'JPX_Gold_Standard_Futures_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_TIP_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_HL_adj_close'),
        ('LME_PB_Close', 'FX_ZARUSD'),
        ('US_Stock_COP_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('US_Stock_OXY_adj_close', 'LME_CA_Close'),
        ('US_Stock_AMP_adj_close', 'LME_ZS_Close'),
        ('LME_AH_Close', 'US_Stock_TRGP_adj_close'),
        ('LME_PB_Close', 'US_Stock_ALB_adj_close'),
        ('US_Stock_VEA_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('US_Stock_NEM_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('FX_GBPNZD', 'LME_CA_Close'),
        ('FX_EURAUD', 'LME_AH_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_TRGP_adj_close'),
        ('US_Stock_IEF_adj_close', 'LME_PB_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_CVE_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_IEF_adj_close'),
        ('LME_AH_Close', 'US_Stock_CVE_adj_close'),
        ('LME_ZS_Close', 'US_Stock_TD_adj_close'),
        ('LME_ZS_Close', 'US_Stock_KMI_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_RSP_adj_close'),
        ('LME_AH_Close', 'US_Stock_OIH_adj_close'),
        ('US_Stock_EWJ_adj_close', 'LME_ZS_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_CVE_adj_close'),
        ('LME_ZS_Close', 'US_Stock_AMP_adj_close'),
        ('LME_AH_Close', 'US_Stock_WPM_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_BKR_adj_close'),
        ('US_Stock_XLB_adj_close', 'LME_ZS_Close'),
        ('FX_NOKEUR', 'LME_PB_Close'),
        ('LME_ZS_Close', 'FX_AUDCHF'),
        ('LME_ZS_Close', 'LME_PB_Close'),
        ('FX_NOKGBP', 'LME_ZS_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_EWY_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'LME_AH_Close'),
        ('LME_AH_Close', 'US_Stock_BNDX_adj_close'),
        ('US_Stock_OKE_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_CA_Close', 'FX_EURUSD'),
        ('LME_CA_Close', 'FX_CADCHF'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_EWY_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_BNDX_adj_close'),
        ('LME_AH_Close', 'US_Stock_NEM_adj_close'),
        ('US_Stock_KMI_adj_close', 'LME_CA_Close'),
        ('FX_GBPNZD', 'JPX_Gold_Standard_Futures_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_ACWI_adj_close'),
        ('US_Stock_EWT_adj_close', 'LME_PB_Close'),
        ('LME_ZS_Close', 'US_Stock_TIP_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_RY_adj_close'),
        ('LME_AH_Close', 'US_Stock_WMB_adj_close'),
        ('FX_CADUSD', 'LME_CA_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'LME_CA_Close'),
        ('LME_PB_Close', 'FX_USDJPY'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_WMB_adj_close'),
        ('FX_EURUSD', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_PB_Close', 'FX_NOKCHF'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_VXUS_adj_close'),
        ('LME_PB_Close', 'FX_AUDJPY'),
        ('LME_CA_Close', 'US_Stock_CAT_adj_close'),
        ('LME_ZS_Close', 'US_Stock_IEF_adj_close'),
        ('FX_CHFJPY', 'LME_ZS_Close'),
        ('LME_PB_Close', 'US_Stock_VT_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_VXUS_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_NUE_adj_close'),
        ('LME_AH_Close', 'US_Stock_VGK_adj_close'),
        ('LME_CA_Close', 'FX_ZAREUR'),
        ('LME_AH_Close', 'US_Stock_EWZ_adj_close'),
        ('LME_ZS_Close', 'US_Stock_WPM_adj_close'),
        ('LME_AH_Close', 'US_Stock_VTV_adj_close'),
        ('US_Stock_COP_adj_close', 'LME_PB_Close'),
        ('LME_CA_Close', 'FX_NOKEUR'),
        ('US_Stock_IAU_adj_close', 'LME_CA_Close'),
        ('LME_CA_Close', 'FX_AUDCHF'),
        ('LME_ZS_Close', 'US_Stock_FCX_adj_close'),
        ('US_Stock_TECK_adj_close', 'LME_CA_Close'),
        ('LME_CA_Close', 'US_Stock_XOM_adj_close'),
        ('LME_ZS_Close', 'FX_GBPUSD'),
        ('US_Stock_ALB_adj_close', 'LME_AH_Close'),
        ('US_Stock_CVX_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_ZS_Close', 'US_Stock_STLD_adj_close'),
        ('US_Stock_ACWI_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_AH_Close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_PB_Close', 'FX_NOKJPY'),
        ('FX_ZARGBP', 'JPX_Gold_Standard_Futures_Close'),
        ('US_Stock_MPC_adj_close', 'LME_ZS_Close'),
        ('FX_AUDJPY', 'LME_ZS_Close'),
        ('LME_CA_Close', 'US_Stock_HL_adj_close'),
        ('US_Stock_EWT_adj_close', 'LME_AH_Close'),
        ('LME_CA_Close', 'US_Stock_TRGP_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_CADJPY'),
        ('LME_PB_Close', 'US_Stock_SLB_adj_close'),
        ('LME_PB_Close', 'LME_AH_Close'),
        ('LME_PB_Close', 'US_Stock_FCX_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_JNK_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_MPC_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_IAU_adj_close'),
        ('LME_ZS_Close', 'US_Stock_VXUS_adj_close'),
        ('US_Stock_EOG_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_PB_Close', 'US_Stock_STLD_adj_close'),
        ('US_Stock_TRGP_adj_close', 'LME_CA_Close'),
        ('LME_AH_Close', 'FX_ZARUSD'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_ENB_adj_close'),
        ('LME_AH_Close', 'US_Stock_ALB_adj_close'),
        ('FX_NZDJPY', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_ZARUSD'),
        ('LME_ZS_Close', 'US_Stock_EWZ_adj_close'),
        ('LME_ZS_Close', 'US_Stock_VTV_adj_close'),
        ('FX_NZDCHF', 'LME_PB_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_ALB_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_SPYV_adj_close'),
        ('US_Stock_RSP_adj_close', 'LME_CA_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_ZARGBP'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_EOG_adj_close'),
        ('US_Stock_DVN_adj_close', 'LME_ZS_Close'),
        ('LME_ZS_Close', 'US_Stock_VALE_adj_close'),
        ('LME_PB_Close', 'US_Stock_VTV_adj_close'),
        ('FX_GBPUSD', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_ZS_Close', 'US_Stock_JNK_adj_close'),
        ('FX_ZAREUR', 'LME_ZS_Close'),
        ('LME_ZS_Close', 'US_Stock_IAU_adj_close'),
        ('US_Stock_OXY_adj_close', 'LME_ZS_Close'),
        ('LME_PB_Close', 'FX_NOKGBP'),
        ('US_Stock_HL_adj_close', 'LME_AH_Close'),
        ('FX_CADJPY', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_AUDCAD'),
        ('US_Stock_OXY_adj_close', 'LME_AH_Close'),
        ('FX_EURGBP', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_USDJPY'),
        ('US_Stock_VXUS_adj_close', 'LME_CA_Close'),
        ('LME_CA_Close', 'US_Stock_EWZ_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_NOKCHF'),
        ('US_Stock_LYB_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_AH_Close', 'FX_NOKCHF'),
        ('US_Stock_EWY_adj_close', 'LME_ZS_Close'),
        ('FX_EURJPY', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_NOKCHF'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_VT_adj_close'),
        ('FX_EURUSD', 'LME_AH_Close'),
        ('LME_AH_Close', 'FX_EURNZD'),
        ('US_Stock_OIH_adj_close', 'LME_CA_Close'),
        ('LME_PB_Close', 'US_Stock_TECK_adj_close'),
        ('LME_CA_Close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_CA_Close', 'US_Stock_VALE_adj_close'),
        ('US_Stock_TECK_adj_close', 'LME_PB_Close'),
        ('LME_CA_Close', 'US_Stock_VGIT_adj_close'),
        ('LME_PB_Close', 'US_Stock_CLF_adj_close'),
        ('LME_PB_Close', 'FX_ZARGBP'),
        ('US_Stock_IEMG_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'LME_ZS_Close'),
        ('LME_AH_Close', 'LME_ZS_Close'),
        ('US_Stock_IEMG_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('US_Stock_TIP_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_PB_Close', 'FX_NOKUSD'),
        ('FX_CADUSD', 'LME_AH_Close'),
        ('LME_ZS_Close', 'FX_USDJPY'),
        ('FX_GBPUSD', 'LME_PB_Close'),
        ('FX_NOKJPY', 'LME_CA_Close'),
        ('US_Stock_OIH_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_AH_Close', 'FX_GBPUSD'),
        ('FX_ZARGBP', 'LME_AH_Close'),
        ('US_Stock_JNK_adj_close', 'LME_ZS_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'LME_AH_Close'),
        ('US_Stock_SPYV_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('US_Stock_BKR_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_FCX_adj_close'),
        ('US_Stock_SLB_adj_close', 'LME_CA_Close'),
        ('US_Stock_IAU_adj_close', 'LME_ZS_Close'),
        ('US_Stock_DE_adj_close', 'LME_CA_Close'),
        ('LME_ZS_Close', 'FX_EURNZD'),
        ('US_Stock_EEM_adj_close', 'LME_PB_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_ACWI_adj_close'),
        ('US_Stock_EOG_adj_close', 'LME_AH_Close'),
        ('US_Stock_RSP_adj_close', 'LME_PB_Close'),
        ('US_Stock_RIO_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_CADJPY', 'LME_PB_Close'),
        ('US_Stock_CVX_adj_close', 'LME_CA_Close'),
        ('FX_GBPJPY', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_AH_Close', 'US_Stock_SLV_adj_close'),
        ('US_Stock_SCCO_adj_close', 'LME_AH_Close'),
        ('LME_PB_Close', 'FX_NZDUSD'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_SLV_adj_close'),
        ('US_Stock_SLB_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_ZS_Close', 'US_Stock_OXY_adj_close'),
        ('US_Stock_HAL_adj_close', 'LME_CA_Close'),
        ('US_Stock_TD_adj_close', 'LME_ZS_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_NOKGBP'),
        ('US_Stock_XLB_adj_close', 'LME_CA_Close'),
        ('FX_NZDJPY', 'LME_CA_Close'),
        ('LME_CA_Close', 'US_Stock_EWT_adj_close'),
        ('US_Stock_HES_adj_close', 'LME_PB_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_HES_adj_close'),
        ('US_Stock_NUE_adj_close', 'LME_CA_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_COP_adj_close'),
        ('FX_AUDUSD', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_CADCHF', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_CADJPY', 'LME_AH_Close'),
        ('US_Stock_EWJ_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('FX_EURCHF', 'LME_CA_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_NZDCHF'),
        ('US_Stock_MS_adj_close', 'LME_PB_Close'),
        ('LME_CA_Close', 'FX_ZARJPY'),
        ('LME_CA_Close', 'US_Stock_WPM_adj_close'),
        ('LME_AH_Close', 'US_Stock_CLF_adj_close'),
        ('LME_ZS_Close', 'US_Stock_SLV_adj_close'),
        ('US_Stock_JNK_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_AH_Close', 'FX_EURJPY'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_CLF_adj_close'),
        ('LME_AH_Close', 'US_Stock_OKE_adj_close'),
        ('LME_CA_Close', 'US_Stock_BNDX_adj_close'),
        ('FX_NZDUSD', 'LME_PB_Close'),
        ('LME_PB_Close', 'FX_ZARCHF'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_DE_adj_close'),
        ('LME_ZS_Close', 'FX_NOKGBP'),
        ('FX_NOKUSD', 'LME_AH_Close'),
        ('US_Stock_NUE_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('US_Stock_VWO_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_CCJ_adj_close'),
        ('LME_CA_Close', 'US_Stock_STLD_adj_close'),
        ('US_Stock_RIO_adj_close', 'LME_PB_Close'),
        ('FX_NOKJPY', 'LME_PB_Close'),
        ('LME_PB_Close', 'US_Stock_LYB_adj_close'),
        ('US_Stock_URA_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_CA_Close', 'US_Stock_RY_adj_close'),
        ('US_Stock_EWZ_adj_close', 'LME_ZS_Close'),
        ('LME_AH_Close', 'US_Stock_EEM_adj_close'),
        ('US_Stock_OKE_adj_close', 'LME_ZS_Close'),
        ('US_Stock_RY_adj_close', 'LME_CA_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_EURCHF'),
        ('LME_AH_Close', 'FX_EURCHF'),
        ('LME_CA_Close', 'US_Stock_VGK_adj_close'),
        ('LME_ZS_Close', 'US_Stock_TECK_adj_close'),
        ('US_Stock_VT_adj_close', 'LME_ZS_Close'),
        ('LME_PB_Close', 'US_Stock_HES_adj_close'),
        ('US_Stock_MS_adj_close', 'LME_AH_Close'),
        ('LME_PB_Close', 'FX_CHFJPY'),
        ('FX_USDJPY', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_AH_Close', 'US_Stock_CAT_adj_close'),
        ('FX_EURGBP', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_CA_Close', 'US_Stock_SLV_adj_close'),
        ('LME_ZS_Close', 'US_Stock_DE_adj_close'),
        ('LME_ZS_Close', 'US_Stock_GLD_adj_close'),
        ('LME_ZS_Close', 'US_Stock_CCJ_adj_close'),
        ('US_Stock_CLF_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_EURJPY', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_ZS_Close', 'FX_NOKUSD'),
        ('US_Stock_XLE_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_ZS_Close', 'US_Stock_MS_adj_close'),
        ('LME_AH_Close', 'US_Stock_VWO_adj_close'),
        ('LME_PB_Close', 'US_Stock_VGIT_adj_close'),
        ('US_Stock_RIO_adj_close', 'LME_AH_Close'),
        ('US_Stock_SPYV_adj_close', 'LME_CA_Close'),
        ('LME_PB_Close', 'US_Stock_URA_adj_close'),
        ('US_Stock_COP_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('US_Stock_XOM_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('US_Stock_VTV_adj_close', 'LME_ZS_Close'),
        ('LME_ZS_Close', 'FX_EURCHF'),
        ('LME_PB_Close', 'FX_AUDUSD'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_HAL_adj_close'),
        ('FX_EURCAD', 'LME_AH_Close'),
        ('US_Stock_DE_adj_close', 'LME_AH_Close'),
        ('FX_ZAREUR', 'LME_CA_Close'),
        ('LME_CA_Close', 'FX_NZDCHF'),
        ('LME_AH_Close', 'US_Stock_XLB_adj_close'),
        ('US_Stock_CVX_adj_close', 'LME_ZS_Close'),
        ('LME_ZS_Close', 'US_Stock_VEA_adj_close'),
        ('LME_ZS_Close', 'US_Stock_CAT_adj_close'),
        ('FX_USDCHF', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_CA_Close', 'US_Stock_GLD_adj_close'),
        ('FX_GBPJPY', 'LME_CA_Close'),
        ('LME_CA_Close', 'US_Stock_OKE_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_BKR_adj_close'),
        ('LME_CA_Close', 'US_Stock_CCJ_adj_close'),
        ('LME_PB_Close', 'US_Stock_VEA_adj_close'),
        ('FX_EURNZD', 'JPX_Gold_Standard_Futures_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_EURCAD'),
        ('US_Stock_EWJ_adj_close', 'LME_AH_Close'),
        ('FX_EURAUD', 'LME_CA_Close'),
        ('FX_GBPNZD', 'JPX_Platinum_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_EURCAD'),
        ('FX_ZAREUR', 'JPX_Gold_Standard_Futures_Close'),
        ('LME_AH_Close', 'FX_ZARCHF'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_NEM_adj_close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_EURGBP'),
        ('LME_ZS_Close', 'US_Stock_HAL_adj_close'),
        ('LME_PB_Close', 'FX_NOKEUR'),
        ('US_Stock_XLE_adj_close', 'LME_PB_Close'),
        ('LME_ZS_Close', 'US_Stock_XLB_adj_close'),
        ('JPX_Gold_Standard_Futures_Close', 'US_Stock_WMB_adj_close'),
        ('US_Stock_NUE_adj_close', 'LME_AH_Close'),
        ('US_Stock_MPC_adj_close', 'LME_PB_Close'),
        ('US_Stock_ENB_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('FX_AUDJPY', 'LME_PB_Close'),
        ('FX_CADCHF', 'LME_CA_Close'),
        ('FX_ZARJPY', 'LME_CA_Close'),
        ('LME_AH_Close', 'US_Stock_EFA_adj_close'),
        ('US_Stock_VALE_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_NZDJPY'),
        ('JPX_Platinum_Standard_Futures_Close', 'US_Stock_EFA_adj_close'),
        ('US_Stock_EEM_adj_close', 'LME_AH_Close'),
        ('FX_CHFJPY', 'LME_AH_Close'),
        ('LME_CA_Close', 'US_Stock_VWO_adj_close'),
        ('LME_CA_Close', 'FX_NZDUSD'),
        ('US_Stock_TIP_adj_close', 'LME_PB_Close'),
        ('US_Stock_WPM_adj_close', 'JPX_Gold_Standard_Futures_Close'),
        ('JPX_Platinum_Standard_Futures_Close', 'FX_CHFJPY'),
        ('US_Stock_ACWI_adj_close', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_USDCHF', 'LME_PB_Close'),
        ('LME_AH_Close', 'JPX_Platinum_Standard_Futures_Close'),
        ('FX_EURJPY', 'LME_ZS_Close'),
        ('LME_ZS_Close', 'FX_EURGBP'),
        ('US_Stock_CVE_adj_close', 'LME_AH_Close'),
        ('US_Stock_FCX_adj_close', 'LME_ZS_Close'),
        ('JPX_Gold_Standard_Futures_Close', 'FX_USDCHF'),
        ('LME_ZS_Close', 'US_Stock_DVN_adj_close'),
        ('US_Stock_LYB_adj_close', 'LME_AH_Close'),
        ('LME_CA_Close', 'LME_ZS_Close'),
        ('FX_AUDCAD', 'JPX_Platinum_Standard_Futures_Close'),
        ('LME_AH_Close', 'FX_GBPNZD')]

    LAGS = {
        "lag1": [f"target_{i}" for i in range(106)],
        "lag2": [f"target_{i}" for i in range(106, 212)],
        "lag3": [f"target_{i}" for i in range(212, 318)],
        "lag4": [f"target_{i}" for i in range(318, 424)],
    }

    LAGS_TARGET = {
        1: 106,
        2: 106,
        3: 106,
        4: 106,
    }
    # fmt: on
    RUN_CV = True

    SEQ_LEN = 8
    VERBOSE = True
    BATCH_SIZE = 32

    LAG_SEQ_LEN = {
        1: 4,
        2: 4,
        3: 16,
        4: 16,
    }

    RETURNS_FEATURES = [
        "Open",
        "Close",
        "Low",
        "High",
        "adj_open",
        "adj_close",
        "adj_low",
        "adj_high",
        "FX_",
    ]

    BASE_PRICE_FEATURES = [
        "Open",
        "Close",
        "Low",
        "High",
    ]

    BASE_OTHER_FEATURES = [
        "Volume",
        "open_interest",
    ]

    IMPT_COL = [
        "US_Stock_DE_adj_low_std_90_252",
        "target_96_return_lag_4_std_252_252",
        "US_Stock_SHEL_adj_low_vol_90_std_10_90",
        "target_251_auto_corr_90_std_252_90",
        "US_Stock_JNK_adj_close_log_ret_return_skew_10_std_252_90",
        "target_63_return_lag_4_std_10_252",
        "US_Stock_CLF_adj_open_vol_10_std_252_10",
        "target_381_return_lag_1_std_90_90",
        "target_385_return_skew_5_std_252_10",
        "US_Stock_DE_adj_open_10_sortino_std_10_252",
        "target_96_return_lag_4_std_10_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sigmoid_diff_std_90_252",
        "US_Stock_JNK_adj_close_log_ret_return_skew_252_std_10_252",
        "FX_ZAREUR_10_sortino_std_10_10",
        "LME_ZS_Close_log_ret_FX_NOKGBP_log_ret_log_ratio_std_90_10",
        "US_Stock_CVX_adj_close_std_252_10",
        "US_Stock_DE_adj_close_sma_10_std_90_252",
        "US_Stock_ENB_adj_close_log_ret_return_lag_5_std_90_252",
        "target_1_return_lag_2_std_90_10",
        "target_184_return_skew_252_std_90_90",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sigmoid_diff_std_252_90",
        "US_Stock_OXY_adj_high_log_ret_return_skew_5_std_10_10",
        "US_Stock_DE_adj_high_std_90_252",
        "US_Stock_DE_adj_high_10_sortino_std_90_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sub_std_252_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sub_std_90_252",
        "target_6_return_lag_2_std_252_90",
        "US_Stock_JNK_adj_low_log_ret_return_skew_252_std_10_252",
        "US_Stock_DE_adj_close_252_sharpe_std_90_252",
        "US_Stock_SLB_adj_open_log_ret_return_skew_5_std_10_10",
        "target_385_return_skew_5_std_10_90",
        "US_Stock_DE_adj_close_std_90_252",
        "US_Stock_XLE_adj_close_log_ret_auto_corr_10_std_10_10",
        "target_141_auto_corr_252_std_10_10",
        "target_46_return_lag_4_std_252_252",
        "JPX_Platinum_Mini_Futures_Close_log_ret_auto_corr_90_std_10_252",
        "US_Stock_JNK_adj_close_log_ret_return_skew_10_std_90_90",
        "US_Stock_DE_adj_close_10_sortino_std_90_90",
        "US_Stock_DE_adj_open_sma_10_std_10_252",
        "US_Stock_EFA_adj_low_log_ret_return_skew_252_std_10_10",
        "FX_ZARCHF_log_ret_JPX_Platinum_Standard_Futures_Close_log_ret_mul_std_10_10",
        "target_46_return_lag_4_std_90_90",
        "ranked_US_Stock_GLD_adj_close_log_ret_LME_PB_Close_log_ret_exp_diff_std_90_10",
        "US_Stock_DE_adj_open_90_sortino_std_10_90",
        "target_108_return_skew_90_std_10_90",
        "target_97_return_lag_4_std_252_252",
        "target_1_return_lag_4_std_90_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_exp_diff_std_10_252",
        "JPX_Platinum_Standard_Futures_Close_log_ret_FX_ZARUSD_log_ret_atan_ratio_std_10_90",
        "US_Stock_DE_adj_low_sma_5_std_90_252",
        "target_263_return_lag_5_std_252_10",
        "US_Stock_MS_adj_open_vol_90_std_90_90",
        "US_Stock_DE_adj_low_90_sharpe_std_252_252",
        "target_1_return_lag_4_std_10_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sigmoid_diff_std_10_252",
        "US_Stock_DE_adj_close_std_90_90",
        "US_Stock_GLD_adj_low_log_ret_return_skew_10_std_10_90",
        "FX_NZDUSD_log_ret_LME_PB_Close_log_ret_sqrt_mul_std_252_90",
        "US_Stock_DE_adj_low_252_sharpe_std_90_252",
        "target_176_auto_corr_90_std_90_10",
        "US_Stock_JNK_adj_close_log_ret_return_skew_10_std_252_10",
        "target_30_auto_corr_252_std_10_10",
        "target_46_return_lag_4_std_252_90",
        "target_36_return_lag_4_std_252_90",
        "US_Stock_EWY_adj_close_log_ret_auto_corr_90_std_90_90",
        "LME_PB_Close_log_ret_FX_NZDUSD_log_ret_sqrt_mul_std_252_90",
        "US_Stock_MS_adj_close_log_ret_return_skew_252_std_10_252",
        "US_Stock_DE_adj_high_5_sortino_std_90_252",
        "target_97_return_lag_4_std_90_252",
        "US_Stock_WPM_obv_90_std_252_90",
        "US_Stock_CVX_adj_low_std_90_10",
        "target_262_auto_corr_90_std_252_10",
        "US_Stock_SHEL_adj_close_vol_90_std_10_90",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sub_std_252_90",
        "US_Stock_IEMG_adj_high_log_ret_return_skew_252_std_10_252",
        "target_1_return_lag_4_std_10_90",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_sigmoid_diff_std_252_252",
        "FX_GBPAUD_log_ret_auto_corr_10_std_90_90",
        "US_Stock_DE_adj_low_10_sortino_std_90_252",
        "target_46_return_lag_4_std_10_90",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sub_std_10_252",
        "US_Stock_ENB_adj_close_log_ret_return_lag_5_std_10_252",
        "US_Stock_DE_adj_open_10_sortino_std_90_90",
        "target_385_return_skew_5_std_10_252",
        "target_1_return_lag_4_std_252_252",
        "target_354_return_skew_252_std_10_90",
        "US_Stock_SLB_adj_open_log_ret_return_skew_5_std_10_252",
        "US_Stock_JNK_adj_close_log_ret_return_skew_10_std_90_10",
        "target_381_return_lag_1_std_90_10",
        "FX_ZARCHF_log_ret_JPX_Platinum_Standard_Futures_Close_log_ret_log_mul_std_10_90",
        "JPX_Platinum_Standard_Futures_Close_log_ret_FX_ZARUSD_log_ret_atan_ratio_std_10_252",
        "target_322_return_skew_90_std_10_10",
        "US_Stock_WPM_obv_90_std_252_252",
        "US_Stock_KGC_obv_90_std_252_10",
        "US_Stock_MS_adj_low_vol_90_std_90_90",
        "FX_EURGBP_log_ret_auto_corr_252_std_10_90",
        "target_416_auto_corr_90_std_90_252",
        "target_101_auto_corr_90_std_10_252",
        "FX_GBPAUD_log_ret_auto_corr_10_std_90_10",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_exp_diff_std_90_252",
        "target_363_return_skew_10_std_10_90",
        "target_36_return_lag_4_std_90_90",
        "US_Stock_SCCO_adj_high_log_ret_return_skew_10_std_90_90",
        "FX_NOKJPY_log_ret_LME_PB_Close_log_ret_harmonic_mean_std_10_10",
        "US_Stock_KGC_obv_90_std_252_90",
        "target_179_return_skew_10_std_90_10",
        "JPX_Gold_Mini_Futures_open_interest_std_90_10",
        "US_Stock_DE_adj_high_sma_10_std_10_252",
        "US_Stock_DE_adj_open_std_90_252",
        "target_415_return_lag_1_std_90_252",
        "US_Stock_XLB_adj_open_log_ret_return_skew_90_std_90_10",
        "FX_GBPAUD_log_ret_auto_corr_10_std_252_10",
        "target_251_auto_corr_90_std_90_90",
        "US_Stock_DVN_adj_close_log_ret_LME_PB_Close_log_ret_norm_diff_std_252_252",
        "target_36_return_lag_4_std_10_252",
        "target_1_return_lag_4_std_90_90",
        "US_Stock_DE_adj_open_sma_10_std_90_90",
        "FX_GBPAUD_log_ret_auto_corr_10_std_252_252",
        "US_Stock_DE_adj_open_10_sortino_std_90_252",
        "LME_AH_Close_vol_252_std_10_10",
        "FX_GBPAUD_log_ret_auto_corr_10_std_252_90",
        "target_385_return_skew_5_std_252_90",
        "US_Stock_DE_adj_high_sma_10_std_90_252",
        "target_96_return_lag_4_std_90_90",
        "target_416_auto_corr_90_std_90_90",
        "US_Stock_DE_adj_low_sma_10_std_90_252",
        "US_Stock_DE_adj_high_90_sharpe_std_252_252",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_exp_diff_std_90_10",
        "target_96_return_lag_4_std_10_90",
        "US_Stock_CVX_adj_close_sma_5_std_252_10",
        "US_Stock_IAU_adj_low_log_ret_return_skew_10_std_10_252",
        "US_Stock_SHEL_adj_high_vol_90_std_10_90",
        "ranked_FX_GBPNZD_log_ret_LME_CA_Close_log_ret_abs_diff_std_90_10",
        "target_292_return_lag_5_std_90_90",
        "US_Stock_DE_adj_close_90_sortino_std_10_90",
        "target_6_return_lag_2_std_90_90",
        "target_179_return_skew_10_std_252_10",
        "US_Stock_DE_adj_open_sma_5_std_90_252",
        "target_292_return_lag_5_std_252_90",
        "target_25_return_lag_4_std_90_252",
        "JPX_Platinum_Standard_Futures_Close_log_ret_FX_ZARUSD_log_ret_mul_std_10_90",
        "target_6_return_lag_2_std_10_252",
        "US_Stock_YINN_adj_open_log_ret_return_skew_252_std_90_90",
        "target_381_return_lag_1_std_252_10",
        "ranked_JPX_Gold_Standard_Futures_Close_log_ret_FX_EURCHF_log_ret_norm_diff_std_252_10",
        "US_Stock_DE_adj_low_sma_10_std_90_90",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sigmoid_diff_std_252_252",
        "ranked_LME_CA_Close_log_ret_US_Stock_VYM_adj_close_log_ret_log_ratio_std_90_10",
        "US_Stock_DE_adj_close_sma_90_std_10_90",
        "target_25_return_lag_4_std_252_252",
        "target_82_auto_corr_252_std_10_10",
        "target_251_auto_corr_90_std_90_252",
        "US_Stock_ALB_adj_open_sma_252_std_252_10",
        "target_264_return_lag_5_std_252_10",
        "target_46_return_lag_4_std_10_252",
        "JPX_Platinum_Standard_Futures_Close_log_ret_US_Stock_JNK_adj_close_log_ret_harmonic_mean_std_252_10",
        "US_Stock_KGC_adj_high_log_ret_return_lag_3_std_252_10",
        "LME_PB_Close_log_ret_FX_NZDUSD_log_ret_sqrt_mul_std_90_90",
        "US_Stock_DE_adj_open_5_sortino_std_90_252",
        "target_390_return_skew_10_std_10_10",
        "US_Stock_DE_adj_high_sma_5_std_90_252",
        "target_96_return_lag_4_std_90_252",
        "US_Stock_CVX_adj_close_5_sortino_std_252_10",
        "US_Stock_OXY_adj_low_log_ret_auto_corr_10_std_10_90",
        "FX_ZARCHF_log_ret_JPX_Platinum_Standard_Futures_Close_log_ret_log_mul_std_10_10",
        "US_Stock_OXY_adj_high_log_ret_auto_corr_10_std_10_90",
        "US_Stock_KGC_obv_90_std_90_10",
        "target_6_return_lag_2_std_252_252",
        "JPX_Gold_Mini_Futures_open_interest_std_90_90",
        "US_Stock_JNK_adj_low_log_ret_return_skew_252_std_10_90",
        "target_392_auto_corr_252_std_90_10",
        "target_292_return_lag_5_std_252_10",
        "target_385_return_skew_5_std_90_252",
        "US_Stock_DE_adj_low_std_90_90",
        "US_Stock_DE_adj_open_sma_10_std_90_252",
        "US_Stock_DE_adj_close_5_sortino_std_90_252",
        "ranked_FX_GBPNZD_log_ret_LME_CA_Close_log_ret_abs_diff_std_252_10",
        "FX_ZARCHF_5_sortino_std_10_90",
        "US_Stock_SHEL_adj_low_vol_90_std_10_252",
        "US_Stock_IAU_adj_low_log_ret_return_skew_10_std_10_90",
        "US_Stock_BSV_adj_open_log_ret_return_lag_3_std_10_90",
        "US_Stock_WPM_adj_high_log_ret_return_skew_90_std_10_10",
        "FX_NOKEUR_vol_90_std_10_90",
        "target_385_return_skew_5_std_252_252",
        "FX_ZARCHF_log_ret_JPX_Platinum_Standard_Futures_Close_log_ret_mul_std_10_90",
        "US_Stock_OXY_adj_low_log_ret_auto_corr_10_std_10_10",
        "target_263_return_lag_5_std_90_10",
        "US_Stock_MS_adj_close_vol_90_std_90_90",
        "US_Stock_DVN_adj_close_log_ret_LME_PB_Close_log_ret_norm_diff_std_90_252",
        "target_358_auto_corr_90_std_90_252",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_sub_std_252_252",
        "target_381_return_lag_1_std_90_252",
        "US_Stock_ENB_adj_close_log_ret_return_lag_5_std_252_252",
        "JPX_Platinum_Standard_Futures_Close_log_ret_FX_ZARUSD_log_ret_log_mul_std_10_90",
        "US_Stock_DE_adj_high_sma_10_std_90_90",
        "target_346_return_skew_252_std_10_10",
        "target_264_return_lag_5_std_252_90",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_exp_diff_std_252_252",
        "US_Stock_DE_adj_low_10_sortino_std_90_90",
        "target_46_return_lag_4_std_90_252",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_exp_diff_std_90_252",
        "JPX_Platinum_Standard_Futures_Close_log_ret_FX_ZARUSD_log_ret_atan_ratio_std_10_10",
        "FX_NZDUSD_log_ret_LME_PB_Close_log_ret_sqrt_mul_std_90_90",
        "LME_ZS_Close_log_ret_auto_corr_252_std_90_10",
        "target_6_return_lag_2_std_10_90",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_exp_diff_std_252_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_exp_diff_std_90_90",
        "US_Stock_DE_adj_high_10_sortino_std_90_90",
        "FX_ZAREUR_sma_5_std_10_90",
        "target_385_return_skew_5_std_10_10",
        "target_42_auto_corr_10_std_10_90",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_sub_std_90_252",
        "US_Stock_DE_adj_close_90_sharpe_std_252_252",
        "US_Stock_MS_adj_close_log_ret_LME_PB_Close_log_ret_sigmoid_diff_std_90_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_exp_diff_std_252_90",
        "US_Stock_DE_adj_open_sma_90_std_10_90",
        "ranked_US_Stock_OKE_adj_close_log_ret_LME_ZS_Close_log_ret_poly3_std_10_252",
        "FX_ZARCHF_sma_5_std_10_90",
        "US_Stock_GDXJ_obv_90_std_252_90",
        "US_Stock_CAT_adj_open_log_ret_return_skew_90_std_90_10",
        "FX_AUDCHF_log_ret_return_skew_10_std_10_252",
        "US_Stock_DE_adj_high_252_sharpe_std_90_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sub_std_90_90",
        "US_Stock_OXY_adj_high_log_ret_auto_corr_10_std_10_252",
        "US_Stock_CVX_adj_close_std_90_10",
        "US_Stock_JNK_adj_close_log_ret_JPX_Platinum_Standard_Futures_Close_log_ret_harmonic_mean_std_252_10",
        "US_Stock_KGC_adj_high_log_ret_return_lag_3_std_90_10",
        "US_Stock_SHEL_adj_close_vol_90_std_10_252",
        "target_97_return_lag_4_std_90_90",
        "target_385_return_skew_5_std_90_90",
        "US_Stock_KGC_obv_90_std_252_252",
        "US_Stock_DE_adj_close_sma_5_std_90_252",
        "target_255_return_skew_10_std_10_10",
        "target_6_return_lag_2_std_90_252",
        "US_Stock_DE_adj_low_sma_90_std_10_90",
        "ranked_US_Stock_GLD_adj_close_log_ret_LME_PB_Close_log_ret_exp_diff_std_252_10",
        "FX_NOKGBP_log_ret_LME_ZS_Close_log_ret_log_ratio_std_90_10",
        "US_Stock_DE_adj_close_10_sortino_std_90_252",
        "target_36_return_lag_4_std_90_252",
        "LME_ZS_Close_log_ret_US_Stock_MS_adj_close_log_ret_sigmoid_diff_std_90_90",
        "target_58_return_lag_4_std_10_252",
        "US_Stock_MS_adj_high_vol_90_std_90_90",
        "target_358_auto_corr_90_std_90_90",
        "US_Stock_SLB_adj_open_log_ret_return_skew_5_std_10_90",
        "LME_PB_Close_log_ret_FX_NOKJPY_log_ret_harmonic_mean_std_10_10",
        "FX_ZAREUR_5_sortino_std_10_90",
        "target_292_return_lag_5_std_90_10",
        "US_Stock_CVX_adj_low_std_252_10",
        "target_36_return_lag_4_std_252_252",
        "target_1_return_lag_2_std_10_10",
        "US_Stock_JNK_adj_close_log_ret_return_skew_252_std_10_90",
        "US_Stock_FXI_adj_open_log_ret_return_skew_252_std_90_90",
        "US_Stock_DE_adj_close_sma_10_std_90_90",
        "FX_GBPAUD_log_ret_auto_corr_10_std_90_252",
        "US_Stock_CAT_adj_close_log_ret_return_skew_90_std_90_10",
        "target_1_return_lag_4_std_252_90",
        "target_42_auto_corr_10_std_10_252",
        "US_Stock_DE_adj_high_10_sortino_std_10_252",
        "US_Stock_ENB_adj_open_log_ret_auto_corr_10_std_90_10",
        "US_Stock_DE_adj_low_90_sortino_std_10_90",
        "target_97_return_lag_4_std_10_252",
        "FX_AUDCHF_log_ret_return_skew_10_std_10_90",
        "JPX_Platinum_Mini_Futures_Low_log_ret_return_skew_10_std_10_252",
        "US_Stock_GDXJ_obv_90_std_252_252",
        "US_Stock_SHEL_adj_open_vol_90_std_10_90",
        "FX_ZAREUR_sma_10_std_10_10",
        "target_264_return_lag_5_std_90_10",
        "US_Stock_DE_adj_low_5_sortino_std_90_252",
        "LME_CA_Close_log_ret_US_Stock_BNDX_adj_close_log_ret_log_ratio_std_10_10",
        "FX_GBPCAD_log_ret_return_skew_10_std_252_10",
    ]
